### ISSUE TITLE
v1.29.1 broke my automations for Auto Fan mode

### ISSUE THREAD

**Issue by KennyH** [dahlb/ha_blueair#191]
### System Health details

System Info: Standard HA Green with latest OS, and latest HACS. I have 311i and 211i BlueAir devices.

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_blueair/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After upgrading  to v1.29.1 my automations no longer work correctly. I cannot set my Blue Air filters to Auto mode anymore.

Auto Fan Mode is not longer available in this update. Was that intended?

### Reproduction steps

1. Create automation to set fan to Auto Fan mode 
2. Manually set fan speed
3. Run automation actions from (1)

Expected: fan goes to Auto
Observed: Fan goes to ~50% speed and is not on Auto mode.
...

### Debug logs

```text
"This entity is no longer being provided by the ha_blueair integration. If the entity is no longer in use, delete it in settings."
Logger: homeassistant.helpers.service
Source: helpers/service.py:303
First occurred: 6:53:43 AM (44 occurrences)
Last logged: 4:31:28 PM

Referenced entities switch.my_311i_max_auto_fan_mode are missing or not currently available
Referenced entities switch.ground_floor_litterbox_auto_fan_mode are missing or not currently available
Referenced entities switch.living_room_3650i_auto_fan_mode are missing or not currently available
```

**Comment by dahlb** [comment]
the switches were removed and this breaking change was described in the release notes, below is a sample service call to turn on auto mode for reference

```
action: fan.set_preset_mode
metadata: {}
data:
  preset_mode: auto
target:
  entity_id: fan.bedroom_fan
```

**Comment by dahlb** [comment]
this is a duplicate of #189

**Comment by KennyH** [comment]
Thanks. I upgraded from an earlier version and the 1.29.1 version didn't contain the breaking changes notes. Sorry to bother you. 

If anyone else has this problem, here is a test automation yaml that broke:

```
alias: test fan auto mode living room
description: ""
triggers: []
conditions: []
actions:
  - type: turn_on
    device_id: cb_REDACTED_de
    entity_id: a0_REDACTED_99
    domain: switch
mode: single
```

And here is one that works now with the latest changes:

```
alias: test fan auto preset mode living room
description: ""
triggers: []
conditions: []
actions:
  - action: fan.set_preset_mode
    metadata: {}
    data:
      preset_mode: auto
    target:
      entity_id: fan.living_room_3650i_fan
mode: single
```
